# Generated by Django 2.0.7 on 2018-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacysms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStatsByDay',
            fields=[
                ('media_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('clip_id', models.BigIntegerField(blank=True, null=True)),
                ('is_rtsp', models.BooleanField()),
                ('is_itunes', models.BooleanField()),
                ('collection_id', models.BigIntegerField(blank=True, null=True)),
                ('instid', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('quality', models.TextField(blank=True, null=True)),
                ('fetch_type', models.TextField(blank=True, null=True)),
                ('is_cam', models.BooleanField()),
                ('country', models.TextField(blank=True, null=True)),
                ('num_hits', models.BigIntegerField()),
                ('num_bytes', models.BigIntegerField()),
            ],
            options={
                'db_table': 'media_stats_by_day',
                'managed': False,
            },
        ),
    ]
